server:
  port: 8080
jwt:
  secret: zhou
  expire: 3000
  except:
    authorised-urls: /login,/renewal
spring:
  jpa:
    properties:
      hibernate:
        show_sql: true
        dialect: org.hibernate.dialect.MySQL5Dialect
        hbm2ddl:
          auto: none #update

  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
  shardingsphere:
    enabled: true
    props:
      sql-show: true
    datasource:
      names: ds0,ds1
#      common:
#        type: com.alibaba.druid.pool.DruidDataSource
      ds0:
        type: com.zaxxer.hikari.HikariDataSource
        jdbc-url: jdbc:mysql://192.168.1.11:3308/test?characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
        username: root
        password: 123
        driver-class-name: com.mysql.cj.jdbc.Driver
      ds1:
        type: com.zaxxer.hikari.HikariDataSource
        jdbc-url: jdbc:mysql://192.168.1.11:3307/test?characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
        username: root
        password: 123
        driver-class-name: com.mysql.cj.jdbc.Driver
    rules:
      readwrite-splitting:

        load-balancers:
          # 负载均衡算法
          round_robin:
            type: ROUND_ROBIN
            # 这里是最神经病的地方, 不配置就报错! 配置吧又不知道配置什么
            props:
              # 你也可以配置 xxx: 123, yyy: 4342 但是必须得有一个属性, 随便编
              default: 0
        data-sources:
          # 这个名字就随便起
          prds:
            # 主库
            write-data-source-name: ds0
            # 从库
            read-data-source-names: ds1
            load-balancer-name: round_robin
mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.zsd.entity
  #开启驼峰命名
  configuration:
    map-underscore-to-camel-case: true